/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FsmDslStandaloneSetup extends FsmDslStandaloneSetupGenerated {

	public static void doSetup() {
		new FsmDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
